spring:
  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
h2:
  tcpServer:
    enabled: true
    port: 9092
  webServer:
    enabled: false
    port: 8082
