spring:
  datasource:
#    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
#h2:
#  tcpServer:
#    enabled: true
#    port: 9092
#  webServer:
#    enabled: false
#    port: 8082
