spring:
  datasource:
    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    data: classpath*:data-h2.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#h2:
#  tcpServer:
#    enabled: true
#    port: 9092
#  webServer:
#    enabled: false
#    port: 8082
