/*
String [] loginIds = {"microsoft.com", "oracle.com", "adobe.com", "pivotal.com", "jetbrains.com"};
String [] productIds = {"1", "2", "3", "4", "5", "6"};
int [] prices = {500, 700, 1000, 1200, 900, 1500};
 */
INSERT INTO USER(IDX, NAME, LOGIN_ID) VALUES(USER_IDX_SEQUENCE.NEXTVAL, '마이크로소프트', 'microsoft.com');
INSERT INTO USER(IDX, NAME, LOGIN_ID) VALUES(USER_IDX_SEQUENCE.NEXTVAL, '오라클', 'oracle.com');
INSERT INTO USER(IDX, NAME, LOGIN_ID) VALUES(USER_IDX_SEQUENCE.NEXTVAL, '아도비', 'adobe.com');
INSERT INTO USER(IDX, NAME, LOGIN_ID) VALUES(USER_IDX_SEQUENCE.NEXTVAL, '피보탈', 'pivotal.com');
INSERT INTO USER(IDX, NAME, LOGIN_ID) VALUES(USER_IDX_SEQUENCE.NEXTVAL, '젯브레인스', 'jetbrains.com');

INSERT INTO PRODUCT(IDX, PRODUCT_NAME, PRODUCT_PRICE) VALUES(PRODUCT_IDX_SEQUENCE.NEXTVAL, '단팥빵', 500);
INSERT INTO PRODUCT(IDX, PRODUCT_NAME, PRODUCT_PRICE) VALUES(PRODUCT_IDX_SEQUENCE.NEXTVAL, '도너츠', 700);
INSERT INTO PRODUCT(IDX, PRODUCT_NAME, PRODUCT_PRICE) VALUES(PRODUCT_IDX_SEQUENCE.NEXTVAL, '소보루빵', 1000);
INSERT INTO PRODUCT(IDX, PRODUCT_NAME, PRODUCT_PRICE) VALUES(PRODUCT_IDX_SEQUENCE.NEXTVAL, '쏘시지빵', 1200);
INSERT INTO PRODUCT(IDX, PRODUCT_NAME, PRODUCT_PRICE) VALUES(PRODUCT_IDX_SEQUENCE.NEXTVAL, '모카빵', 900);
INSERT INTO PRODUCT(IDX, PRODUCT_NAME, PRODUCT_PRICE) VALUES(PRODUCT_IDX_SEQUENCE.NEXTVAL, '피자빵', 1500);